package Formulario;

import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.time.format.DateTimeFormatter;
import java.util.List;
/**
 *
 * @author TDFM
 */
public class Empleados extends javax.swing.JFrame {
    Conexion conexionPostgres = new Conexion();
    Connection con;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Empleados.class.getName());

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        try{
            con = conexionPostgres.getConexion();
        }catch (SQLException e){
                   e.getMessage();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLid = new javax.swing.JLabel();
        LBLnombre = new javax.swing.JLabel();
        LBLapellido = new javax.swing.JLabel();
        LBLcargo = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        LBLtelefono = new javax.swing.JLabel();
        LBLdireccion = new javax.swing.JLabel();
        LBLestado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        LBLfechaIngreso = new javax.swing.JLabel();
        LBLsalario = new javax.swing.JLabel();
        LBLemail = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        BTNingresar = new javax.swing.JButton();
        BTNmodificar = new javax.swing.JButton();
        BTNconsultar = new javax.swing.JButton();
        BTNeliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLid.setText("ID");

        LBLnombre.setText("Nombre");

        LBLapellido.setText("Apellido");

        LBLcargo.setText("Cargo");

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Mesero", "Cajero" }));
        cbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoActionPerformed(evt);
            }
        });

        LBLtelefono.setText("Telefono");

        LBLdireccion.setText("Direccion");

        LBLestado.setText("Estado");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        LBLfechaIngreso.setText("Fecha de ingreso");

        LBLsalario.setText("Salario");

        LBLemail.setText("Email");

        txtId.setText(" ");

        txtNombre.setText(" ");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setText(" ");

        txtTelefono.setText(" ");

        txtDireccion.setText(" ");

        txtFechaIngreso.setText(" ");
        txtFechaIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFechaIngresoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaIngresoMousePressed(evt);
            }
        });

        txtSalario.setText(" ");

        txtEmail.setText(" ");

        BTNingresar.setText("Ingresar");
        BTNingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNingresarActionPerformed(evt);
            }
        });

        BTNmodificar.setText("Modificar");
        BTNmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmodificarActionPerformed(evt);
            }
        });

        BTNconsultar.setText("Consultar");
        BTNconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconsultarActionPerformed(evt);
            }
        });

        BTNeliminar.setText("Eliminar");
        BTNeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLapellido)
                            .addComponent(LBLtelefono)
                            .addComponent(LBLsalario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LBLid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addComponent(LBLnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(LBLdireccion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLfechaIngreso)
                            .addComponent(LBLemail)
                            .addComponent(LBLcargo)
                            .addComponent(LBLestado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTelefono)
                            .addComponent(txtApellido)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre)
                            .addComponent(txtFechaIngreso)
                            .addComponent(txtSalario)
                            .addComponent(txtEmail))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNconsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNeliminar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLnombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLapellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLcargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLtelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLdireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLestado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLfechaIngreso)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLsalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLemail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNingresar)
                    .addComponent(BTNmodificar)
                    .addComponent(BTNconsultar)
                    .addComponent(BTNeliminar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BTNingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNingresarActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String cargo = (String) cbCargo.getSelectedItem();
            String telefono = txtTelefono.getText();            
            String direccion = txtDireccion.getText();            
            String estadoTxt = (String) cbEstado.getSelectedItem();
            String fechaTxt = txtFechaIngreso.getText().trim();                        
            String salarioTxt = txtSalario.getText();
            String email = txtEmail.getText();
            //Convertir el ComboBox a booleano (o sea de 2 estados)
            boolean estado = estadoTxt.equalsIgnoreCase("Activo"); 
            //Darle formato a la fecha
            java.sql.Date fecha_ingreso = java.sql.Date.valueOf(fechaTxt);              
            //Convertir el JtextField a double (numérico)
            double salario = Double.parseDouble(salarioTxt.trim()); 
         


            String qry = "INSERT INTO marinasrestaurant.empleados(nombre, apellido, cargo, telefono, direccion, estado, fecha_ingreso, salario, email)"
                    +" values(?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement ps = con.prepareStatement(qry);
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setString(3, cargo);
            ps.setString(4, telefono);
            ps.setString(5, direccion);
            ps.setBoolean(6, estado);
            ps.setDate(7, fecha_ingreso);            
            ps.setDouble(8, salario);
            ps.setString(9, email);

            int filasInsertadas = ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Total de registros insertados"+filasInsertadas);
            ps.close();

        }catch (SQLException e){
                   e.getMessage();
        }        
    }//GEN-LAST:event_BTNingresarActionPerformed

    private void BTNconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconsultarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = txtNombre.getText().trim();
            
            String qry = "SELECT * FROM marinasrestaurant.empleados WHERE LOWER(nombre) ILIKE LOWER(?)";

            try (PreparedStatement ps = con.prepareStatement(qry)) {
                ps.setString(1, "%" + nombre + "%");
                
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        String apellido = rs.getString("apellido");
                        String cargo = rs.getString("cargo");
                        String telefono = rs.getString("telefono");
                        String direccion = rs.getString("direccion");
                        String estado = rs.getString("estado");
                        String fecha_ingreso = rs.getString("fecha_ingreso");
                        String salario = rs.getString("salario");
                        String email = rs.getString("email");
                        String id = rs.getString("empleado_id");
                        txtApellido.setText(apellido);
                        cbCargo.setSelectedItem(cargo);
                        txtTelefono.setText(telefono);
                        txtDireccion.setText(direccion);
                        cbEstado.setSelectedItem(estado);
                        txtFechaIngreso.setText(fecha_ingreso);
                        txtSalario.setText(salario);
                        txtEmail.setText(email);
                        txtId.setText(id);
            
            JOptionPane.showMessageDialog(this, "Registro encontrado");
            JOptionPane.showMessageDialog(this, nombre);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el empleado " + nombre);
                }
            }
        }

        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }        
    }//GEN-LAST:event_BTNconsultarActionPerformed

    private void BTNeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeliminarActionPerformed
        // TODO add your handling code here:
    try{    
        String nombre = txtNombre.getText().trim();
        
        String qry = "DELETE FROM marinasrestaurant.empleados WHERE LOWER(nombre) ILIKE LOWER(?)";

        PreparedStatement ps = con.prepareStatement(qry);
        ps.setString(1, "%" + nombre + "%");

        int filasActualizadas = ps.executeUpdate();

        if (filasActualizadas > 0) {
            JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
            } else {
            JOptionPane.showMessageDialog(null, "No se encontró un empleado de nombre " + nombre);
            }
        
        ps.close();

        }catch (SQLException e){
                   e.getMessage();
        }
    }//GEN-LAST:event_BTNeliminarActionPerformed

    private void BTNmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmodificarActionPerformed
        // TODO add your handling code here:
        try{
            String idempleado = txtId.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String cargo = (String) cbCargo.getSelectedItem();
            String telefono = txtTelefono.getText();            
            String direccion = txtDireccion.getText();            
            String estadoTxt = (String) cbEstado.getSelectedItem();
            String fechaTxt = txtFechaIngreso.getText().trim();                        
            String salarioTxt = txtSalario.getText();
            String email = txtEmail.getText();
            int id = Integer.parseInt(idempleado.trim());            
            //Convertir el ComboBox a booleano (o sea de 2 estados)
            boolean estado = estadoTxt.equalsIgnoreCase("Activo"); 
            //Darle formato a la fecha
            java.sql.Date fecha_ingreso = java.sql.Date.valueOf(fechaTxt);              
            //Convertir el JtextField a double (numérico)
            double salario = Double.parseDouble(salarioTxt.trim()); 

            String qry = "UPDATE marinasrestaurant.empleados SET nombre=?, apellido=?, cargo=?, telefono=?, direccion=?, estado=?, fecha_ingreso=?, salario=?, email=? WHERE empleado_id=?";

            PreparedStatement ps = con.prepareStatement(qry);
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setString(3, cargo);
            ps.setString(4, telefono);
            ps.setString(5, direccion);
            ps.setBoolean(6, estado);
            ps.setDate(7, fecha_ingreso);            
            ps.setDouble(8, salario);
            ps.setString(9, email);
            ps.setInt(10, id);

            int filasActualizadas = ps.executeUpdate();

        if (filasActualizadas > 0) {
            JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
            } else {
            JOptionPane.showMessageDialog(null, "No se encontró un empleado con id " + id);
            }

        ps.close();

        }catch (SQLException e){
                   e.getMessage();
        }
    }//GEN-LAST:event_BTNmodificarActionPerformed

    private void txtFechaIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaIngresoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaIngresoMouseEntered

    private void txtFechaIngresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaIngresoMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ingrese año-mes-día");        
    }//GEN-LAST:event_txtFechaIngresoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Empleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNconsultar;
    private javax.swing.JButton BTNeliminar;
    private javax.swing.JButton BTNingresar;
    private javax.swing.JButton BTNmodificar;
    private javax.swing.JLabel LBLapellido;
    private javax.swing.JLabel LBLcargo;
    private javax.swing.JLabel LBLdireccion;
    private javax.swing.JLabel LBLemail;
    private javax.swing.JLabel LBLestado;
    private javax.swing.JLabel LBLfechaIngreso;
    private javax.swing.JLabel LBLid;
    private javax.swing.JLabel LBLnombre;
    private javax.swing.JLabel LBLsalario;
    private javax.swing.JLabel LBLtelefono;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
