package Formulario;

import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.view.JasperViewer;

public class Pedido extends javax.swing.JFrame {
    Conexion conexionPostgres = new Conexion();
    Connection con;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pedido.class.getName());

    public Pedido() {
        initComponents();
        try{
            con = conexionPostgres.getConexion();
        }catch (SQLException e){
                   e.getMessage();
      }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNgenerarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTproductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        LBLtipografia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBLnit = new javax.swing.JLabel();
        LBLdireccionEmpresa = new javax.swing.JLabel();
        LBLleyenda = new javax.swing.JLabel();
        LBLcliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        LBLtelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        LBLdireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        Cerrar = new javax.swing.JButton();
        BTNagregarProducto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LBLfacturaNo = new javax.swing.JLabel();
        txtFacturaNo = new javax.swing.JTextField();
        BTNbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNgenerarFactura.setText("Generar Factura");
        BTNgenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNgenerarFacturaActionPerformed(evt);
            }
        });

        JTproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Precio Unitario", "Total"
            }
        ));
        JTproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTproductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JTproductos);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LBLtipografia.setBackground(new java.awt.Color(51, 51, 255));
        LBLtipografia.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        LBLtipografia.setForeground(new java.awt.Color(0, 153, 153));
        LBLtipografia.setText("Marinas Restraurant");
        LBLtipografia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LBLnit.setText("NIT: 3169315-0");

        LBLdireccionEmpresa.setText("Cañas Viejas, San Jerónimo, Baja Verapaz");

        LBLleyenda.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LBLleyenda.setText("\"Los mejores en mariscos\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLtipografia)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)
                        .addGap(102, 102, 102)
                        .addComponent(LBLnit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(LBLdireccionEmpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLleyenda)
                        .addGap(141, 141, 141)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLtipografia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLnit)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLdireccionEmpresa)
                .addGap(18, 18, 18)
                .addComponent(LBLleyenda)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        LBLcliente.setText("Cliente:");

        txtCliente.setText(" ");

        LBLtelefono.setText("Tel:");

        txtTelefono.setText(" ");

        LBLdireccion.setText("Dirección:");

        txtDireccion.setText(" ");

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        BTNagregarProducto.setText("Agregar Producto");
        BTNagregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarProductoActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Producto");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LBLfacturaNo.setText("Factura No.");

        txtFacturaNo.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLfacturaNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFacturaNo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLfacturaNo)
                    .addComponent(txtFacturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNbuscar.setText("Buscar");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(BTNagregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNgenerarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBLcliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNbuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBLtelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LBLdireccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDireccion)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLcliente)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNbuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLtelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLdireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTNagregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNgenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNgenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNgenerarFacturaActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "1234")) {
                String reportPath = "C:\\Users\\TDFM\\JaspersoftWorkspace\\MyReports\\JrEmpleados.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_BTNgenerarFacturaActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = txtCliente.getText().trim();
            
            String qry = "SELECT * FROM marinasrestaurant.clientes WHERE LOWER(nombre) ILIKE LOWER(?)";

            try (PreparedStatement ps = con.prepareStatement(qry)) {
                ps.setString(1, "%" + nombre + "%");
                
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        String telefono = rs.getString("telefono");
                        String direccion = rs.getString("direccion");
                        txtTelefono.setText(telefono);
                        txtDireccion.setText(direccion);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el cliente " + nombre);
                }
            }
        }
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }        
    }//GEN-LAST:event_BTNbuscarActionPerformed

    private void BTNagregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarProductoActionPerformed
        // TODO add your handling code here:
    try {
        // 🔹 Asegurar conexión válida y autocommit activado
        if (con == null || con.isClosed()) {
            Conexion conexionPostgres = new Conexion();
            con = conexionPostgres.getConexion();
        }
        con.setAutoCommit(true);

        // 🔹 Buscar el ID del cliente según el nombre ingresado
        String nombreCliente = txtCliente.getText().trim();
        int clienteId = 0;

        String qryCliente = "SELECT cliente_id FROM marinasrestaurant.clientes WHERE LOWER(nombre) ILIKE LOWER(?)";
        PreparedStatement psCliente = con.prepareStatement(qryCliente);
        psCliente.setString(1, "%" + nombreCliente + "%");
        ResultSet rsCliente = psCliente.executeQuery();

        if (rsCliente.next()) {
            clienteId = rsCliente.getInt("cliente_id");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el cliente: " + nombreCliente);
            rsCliente.close();
            psCliente.close();
            return;
        }
        rsCliente.close();
        psCliente.close();

        // 🔹 Calcular total general de la factura
        int empleadoId = 1; // cambia este ID según tu lógica
        double totalFactura = 0;

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) JTproductos.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 4) != null) {
                totalFactura += Double.parseDouble(modelo.getValueAt(i, 4).toString());
            }
        }

        String sqlFactura = "INSERT INTO marinasrestaurant.facturas (cliente_id, empleado_id, total) VALUES (?, ?, ?) RETURNING factura_id";
        PreparedStatement psFactura = con.prepareStatement(sqlFactura);
        psFactura.setInt(1, clienteId);
        psFactura.setInt(2, empleadoId);
        psFactura.setDouble(3, totalFactura);

        ResultSet rs = psFactura.executeQuery();
        int facturaId = 0;
        if (rs.next()) {
            facturaId = rs.getInt("factura_id");
        }
        rs.close();
        psFactura.close();

        if (facturaId == 0) {
            JOptionPane.showMessageDialog(null, "No se pudo generar la factura. Verifica la conexión o la tabla.");
            return;
        }

        String sqlDetalle = "INSERT INTO marinasrestaurant.detalle_factura (factura_id, producto_id, cantidad, precio_unitario) VALUES (?, ?, ?, ?)";
        PreparedStatement psDetalle = con.prepareStatement(sqlDetalle);

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0) == null) continue;

            int productoId = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(modelo.getValueAt(i, 3).toString());

            psDetalle.setInt(1, facturaId);
            psDetalle.setInt(2, productoId);
            psDetalle.setInt(3, cantidad);
            psDetalle.setDouble(4, precio);
            psDetalle.addBatch();
        }
        psDetalle.executeBatch();
        psDetalle.close();

        JOptionPane.showMessageDialog(null, "✅ Factura generada exitosamente (ID: " + facturaId + ")");
        modelo.setRowCount(0); // limpiar la tabla

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "❌ Error SQL al generar factura:\n" + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "⚠️ Error de formato en los datos:\n" + e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "⚠️ Error inesperado:\n" + e.getMessage());
            }
    }//GEN-LAST:event_BTNagregarProductoActionPerformed

    private void JTproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTproductosKeyReleased
        // TODO add your handling code here:
    int fila = JTproductos.getSelectedRow();
    int columna = JTproductos.getSelectedColumn();

    // Solo reaccionar si se edita la columna de ID (columna 0)
    if (columna == 0 && fila >= 0) {
        try {
            Object valor = JTproductos.getValueAt(fila, 0);
            if (valor == null) return;
            int idProducto = Integer.parseInt(valor.toString().trim());

            String qry = "SELECT nombre_producto, precio FROM marinasrestaurant.productos WHERE producto_id = ?";
            PreparedStatement ps = con.prepareStatement(qry);
            ps.setInt(1, idProducto);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String descripcion = rs.getString("nombre_producto");
                double precio = rs.getDouble("precio");

                JTproductos.setValueAt(descripcion, fila, 1);
                JTproductos.setValueAt(precio, fila, 3);
            } else {
                JTproductos.setValueAt("No encontrado", fila, 1);
                JTproductos.setValueAt(null, fila, 3);
            }
            rs.close();
            ps.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar producto: " + e.getMessage());
        }
    }

    if (columna == 2 && fila >= 0) {
        try {
            int cantidad = Integer.parseInt(JTproductos.getValueAt(fila, 2).toString());
            double precio = Double.parseDouble(JTproductos.getValueAt(fila, 3).toString());
            double total = cantidad * precio;
            JTproductos.setValueAt(total, fila, 4);
            } catch (Exception e) {
          }
        }        
    }//GEN-LAST:event_JTproductosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNagregarProducto;
    private javax.swing.JButton BTNbuscar;
    private javax.swing.JButton BTNgenerarFactura;
    private javax.swing.JButton Cerrar;
    private javax.swing.JTable JTproductos;
    private javax.swing.JLabel LBLcliente;
    private javax.swing.JLabel LBLdireccion;
    private javax.swing.JLabel LBLdireccionEmpresa;
    private javax.swing.JLabel LBLfacturaNo;
    private javax.swing.JLabel LBLleyenda;
    private javax.swing.JLabel LBLnit;
    private javax.swing.JLabel LBLtelefono;
    private javax.swing.JLabel LBLtipografia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFacturaNo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
